// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 账户表
type Account struct {
	ID int64 `json:"id"`
	// 所有者
	Owner string `json:"owner"`
	// 余额
	Balance int64 `json:"balance"`
	// 货币
	Currency string `json:"currency"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 余额明细
type Entry struct {
	ID int64 `json:"id"`
	// 账户ID
	AccountID int64 `json:"account_id"`
	// 变动金额，正代表入，负代表出
	Amount int64 `json:"amount"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// 交易记录
type Transfer struct {
	ID int64 `json:"id"`
	// 出金账户ID
	FromAccountID int64 `json:"from_account_id"`
	// 入金账户ID
	ToAccountID int64 `json:"to_account_id"`
	// 交易金额
	Amount int64 `json:"amount"`
	// 创建时间
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
